### ISSUE TITLE
Explore swagger

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/pinpoint#105]
https://github.com/go-swagger/go-swagger

💥

**Comment by suujia** [comment]
Swagger manages REST API organization and enforces a standard. Main features include:
1. Organized interactive UI view that you can test calls when started. this: http://petstore.swagger.io 
2. Code generation - server/client from `yml` specification files  
Will do more research. Might be too much change for this project lol

**Comment by bobheadxi** [comment]
we have specifications in #135, still considering if we should make use of the OAS codegen
