### ISSUE TITLE
Attach request-id to all gRPC requests

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/pinpoint#67]
chi generates a request-id for us, this should be attached to gateway->core requests to enable better logging

this can be done via `context` - see #101

**Comment by srijonsaha** [comment]
@bobheadxi I think this is already done? In gateway logs I see a `request-id`. But is the core logs supposed to contain a `request-id` as well?

**Comment by bobheadxi** [comment]
yeah thats the idea - it would let us set up some kind of distributed trace, and track events across multiple services/instances. we could use some [fancier tools](https://opentracing.io/) but yolo
