### ISSUE TITLE
creating repeat users doesn't raise an error

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/pinpoint#78]

**Comment by leesw98** [comment]
Cannot duplicate. Does error.
<img width="374" alt="Screen Shot 2019-03-16 at 1 00 25 PM" src="https://user-images.githubusercontent.com/19914676/54480897-8e316800-47eb-11e9-92e5-7fae02870053.png">

**Comment by leesw98** [comment]
```
{
	"code":400,
	"request_id":"dhcp-128-189-197-104.ubcsecure.wireless.ubc.ca/MV2g7MkcY6-000013",
	"message":"unable to validate credentials: email does not appear to be a valid email"
}
```

**Comment by bobheadxi** [comment]
API error message doesn't look great, however - maybe it should say account already exists?
