### ISSUE TITLE
Flesh out API hierarchy

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/pinpoint#95]
look into what `chi` is capable of and come up with a more solid draft of API routes that will accommodate our needs the best.

Document here: https://github.com/ubclaunchpad/pinpoint/wiki/API - there's a few already in implemented

**Comment by adesouky** [comment]
Review changes on https://github.com/ubclaunchpad/pinpoint.wiki.git

**Comment by bobheadxi** [comment]
looks good to me, great work!
